export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const SET_ACCOUNT = 'SET_ACCOUNT';

///////// PETS /////////

export const SET_PET = 'SET_PET';
export const REQUEST_ADD_PET = 'REQUEST_ADD_PET';
export const REQUEST_GET_PETS = 'REQUEST_GET_PETS';
export const RECEIVE_GET_PETS = 'RECEIVE_GET_PETS';
export const SELECTED_PET = 'SELECTED_PET';
export const REQUEST_GET_PET = 'REQUEST_GET_PET';
export const RECEIVE_GET_PET = 'RECEIVE_GET_PET';
export const REQUEST_UPDATE_PET = 'REQUEST_UPDATE_PET';
export const REQUEST_DELETE_PET = 'REQUEST_DELETE_PET';
